/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.solr.client.solrj.SolrServerException;
import org.apache.solr.common.SolrDocument;
import org.apache.solr.common.SolrDocumentList;
import practica.Solr;

/**
 *
 * @author AAHG-PORTATIL
 */
public class VistaBuscador extends javax.swing.JFrame {

    /**
     * Creates new form VistaBuscador
     */
    public VistaBuscador() {
        setSize(getWidth(), getHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jComboBox_campoBusqueda = new javax.swing.JComboBox<>();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_resultadoConsulta = new javax.swing.JTextArea();
        jTextField_textoConsulta = new javax.swing.JTextField();
        jLabel_titulo = new javax.swing.JLabel();
        jTextField_nomColeccion = new javax.swing.JTextField();
        jLabel_coleccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox_campoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "texto" }));
        jComboBox_campoBusqueda.setSelectedIndex(1);
        jComboBox_campoBusqueda.setToolTipText("Campo por el que queremos realizar la Consulta");
        jComboBox_campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_campoBusquedaActionPerformed(evt);
            }
        });

        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jTextArea_resultadoConsulta.setColumns(20);
        jTextArea_resultadoConsulta.setRows(5);
        jScrollPane1.setViewportView(jTextArea_resultadoConsulta);

        jTextField_textoConsulta.setToolTipText("Texto de la Consulta");

        jLabel_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo.setText("Buscador Solr");
        jLabel_titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextField_nomColeccion.setText("coleccionPrueba");

        jLabel_coleccion.setText("Colección:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_coleccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_nomColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(jComboBox_campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_textoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_buscar)
                                .addGap(0, 231, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_textoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar)
                    .addComponent(jComboBox_campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nomColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_coleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_campoBusquedaActionPerformed
        this.jButton_buscar.doClick(); // Para que cuando pulsemos ENTER en 'campoBusqueda' se pulse el boton 'Buscar'
    }//GEN-LAST:event_jComboBox_campoBusquedaActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        
        StringBuilder salida=new StringBuilder(); // Salida de la Consola que ahora mostramos en el Frame
        
        String nomColeccion = this.jTextField_nomColeccion.getText();
        String textoConsulta = this.jTextField_textoConsulta.getText();
        String campoBusqueda = this.jComboBox_campoBusqueda.getSelectedItem().toString();
        
        SolrDocumentList listaDocumentos = new SolrDocumentList();
        try
        {
            listaDocumentos = Solr.realizarConsultaVisual(nomColeccion, textoConsulta, campoBusqueda);
            
            for (SolrDocument d : listaDocumentos)
            {
                salida.append(String.format("\n\nDocumento " + d.getFieldValue("id") + ": "));
                salida.append(String.format("\n\n" + d.getFieldValue("texto")));
                
                this.jTextArea_resultadoConsulta.setText(salida.toString());
            }
        }
        catch (SolrServerException ex)
        {
            Logger.getLogger(VistaBuscador.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IOException ex)
        {
            Logger.getLogger(VistaBuscador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton_buscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_buscar;
    public javax.swing.JComboBox<String> jComboBox_campoBusqueda;
    private javax.swing.JLabel jLabel_coleccion;
    public javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea_resultadoConsulta;
    public javax.swing.JTextField jTextField_nomColeccion;
    public javax.swing.JTextField jTextField_textoConsulta;
    // End of variables declaration//GEN-END:variables
}
